### ISSUE TITLE
initrd-magisk loop in "Initialize system environment....."

### ISSUE THREAD

**Issue by Roze061** [HuskyDG/initrd-magisk#13]
Hello I'm using initrd-magisk v1.15 with cm14.1-r5 kernel default
initrd-magisk loop in "Initialize system environment....."
```
EXT4-fs (sda4) couldn't mount as ext3 due to feature incompatibilities
```
Default initrd from iso work and initrd-magisk work with other os I'm testing.
For now I'm only get problem with initrd-magisk+cm14.1-r5 (previous version not tested)

grub code
```
kernel /cm14/kernel  quiet root=/dev/ram0 androidboot.selinux=permissive buildvariant=userdebug ROOT=/dev/sda4 SRC=/cm14
initrd /cm14/initrd.img
```

I can send you initrd_real.img and ramdisk.img if you want.
and I already verify if iso not corrupt

**Comment by Roze061** [comment]
I'm trying cm14.1-r5 with initrd-magisk v1.6, not looping but I still can see this from DEBUG=3
```
EXT4-fs (sda4) couldn't mount as ext3 due to feature incompatibilities
 found at /dev/sda4
EXT4-fs (loop0) couldn't mount as ext3 due to feature incompatibilities
```
Magisk installed and...

**Comment by HuskyDG** [comment]
Can you send your `initrd.img`, thanks

**Comment by Roze061** [comment]
![cm-x86_64-14.1-r5.zip](https://github.com/HuskyDG/initrd-magisk/files/8735831/cm-x86_64-14.1-r5.zip)
Same from iso

**Comment by Roze061** [comment]
@HuskyDG 
Sorry I found the problem. in the end function `check_root()` if boot-magisk.img not found zcat raised errorlevel. I not know why and I run zcat boot.img.gz with path completion in DEBUG boot $? return 0, but the size is 0 after I boot in linux. in linux I run zcat and I get this file
```
# sha512sum
5590b1c34105cf61f9fd05acc35e60c53c1268512a60b5829d7cc7ba11297500e1136bad824e2616bb70d57e97a167b25b9a13f894e087e4857a58a452bde94c  boot-magisk.img
```
[for the message it's probably due to mount without adding type](https://github.com/HuskyDG/initrd-magisk/issues/13#issuecomment-1132365162)
[init_debug.diff.txt](https://github.com/HuskyDG/initrd-magisk/files/8741561/init_debug.diff.txt)
and there are similarities v1.6 with the original initrd.img

**Comment by HuskyDG** [comment]
> 

if you can fix, you can fork repo and make pull request

**Comment by HuskyDG** [comment]
you can test your changes immediately in GitHub's Actions tab

**Comment by Roze061** [comment]
can initrd-magisk work without boot-magisk.img even after boot.img.gz is used it still doesn't exist
Is there any impact if I ignore boot-magisk.img

**Comment by HuskyDG** [comment]
> can initrd-magisk work without boot-magisk.img even after boot.img.gz is used it still doesn't exist Is there any impact if I ignore boot-magisk.img

you boot android from iso (live mode) or not?

**Comment by Roze061** [comment]
> you boot android from iso (live mode)?

No. I installed in harddisk sda4 and unsquash system.sfs

> I run zcat boot.img.gz with path completion in DEBUG boot $? return 0, but the size is 0

maybe the cause is zcat trying to write boot.img.gz in read only mnt SRC

**Comment by HuskyDG** [comment]
sorry for let you wait,
try https://github.com/HuskyDG/initrd-magisk/commit/7f9f17250392b47d58abaf0f0881e31a57abf309

**Comment by HuskyDG** [comment]
https://github.com/HuskyDG/initrd-magisk/actions/runs/2391222999

**Comment by HuskyDG** [comment]
are you still there?
