### ISSUE TITLE
Kernel panic: Unable to mount root fs on unknown-block

### ISSUE THREAD

**Issue by nitanmarcel** [HuskyDG/initrd-magisk#16]
I'm trying to root an android-x86 installation running with qemu and virt-manager but I can't seem to make it work. No idea what Android-X84 directory means so I've decompiled the bootable iso and replaced initrd from there but upon booting Magisk wasn't yet installed.

**Comment by nitanmarcel** [comment]
I feel so dumb. I haven't followed the instructions correctly, so I forgot to rename the original initrd to initrd_real.

**Comment by nitanmarcel** [comment]
Doesn't boot after I opened magisk and it asked me to reboot :(

![image](https://user-images.githubusercontent.com/41646249/187310968-1ef5fb2c-815b-45fe-a114-cf449c664005.png)

**Comment by HuskyDG** [comment]
dmesg?

**Comment by nitanmarcel** [comment]
> dmesg?

Will send once I figure out how to take that from qemu
