### ISSUE TITLE
initrd-magisk error and reboot and capslock blink 5 times "Initialize system environment..... error reboot in 5 sec

### ISSUE THREAD

**Issue by TukangM** [HuskyDG/initrd-magisk#17]
![image](https://user-images.githubusercontent.com/91467886/192289564-e7a035c2-fbe0-4d26-86d8-2d499690d48f.png)
and this is my parameters on grub2win

![image](https://user-images.githubusercontent.com/91467886/192290018-16bf1426-52cf-4882-9bf7-b0a1a7af8e82.png)

**Comment by TukangM** [comment]
7 hours?

**Comment by HuskyDG** [comment]
Not enough info

**Comment by TukangM** [comment]
> Not enough info

right.

It looks like I deleted the original initrd.img and didn't rename it to initrd_real.img.
