### ISSUE TITLE
where is "Android-x86 directory"?

### ISSUE THREAD

**Issue by protocold** [HuskyDG/initrd-magisk#18]
I have installed Bliss OS 14.3 on the internal emmc of my windows 10 tablet and trying to get root to work.. came across this and when I try to follow the how to doc at https://github.com/HuskyDG/initrd-magisk/wiki/How-to-install-initrd-magisk

said:

In Android-x86 directory, rename initrd.img to initrd_real... 

where is this "Android-x86 directory" please?

**Comment by TukangM** [comment]
Mount extfs drive

**Comment by TukangM** [comment]
Btw. BlissOS 14+ rooted with magisk (rusty-magisk) on ramdisk.img. So yeah. Magisk huskydg (initrd.img) will be overwritten by rusty-magisk and make magisk unable to read magisk root
