### ISSUE TITLE
Modules are missing after a reboot

### ISSUE THREAD

**Issue by slonopot** [HuskyDG/initrd-magisk#30]
Well, the title says it all. I use BlissOS 15.8.5 (Android 12L) and I need to install Magisk there. The issue is that no matter how I install Magisk and modules, they always disappear after a reboot: they are available straight after installation, they are active after the first reboot and they are gone on the next reboot.

What I've tried so far:

- initrd-magisk 1.19 + Magisk Delta stable/canary/debug + unpacked system from sfs to img + switched versions here and there
- Magisk Delta debug + KernelSu root + Direct install into system
- Putting unpacked modules in /data/adb/modules in DEBUG mode
- Different modules, Zygisk on/off

I also have a strong suspicion that it's a rom-specific issue but I'm unable to find any info about it in any discussion there.

These logs are from the version that directly installs into system, I can get logs from initrd version if required. I can also provide access to the VM if needed.

[magisk_log_module_active.log](https://github.com/HuskyDG/initrd-magisk/files/11714897/magisk_log_module_active.log)
[magisk_log_module_gone.log](https://github.com/HuskyDG/initrd-magisk/files/11714898/magisk_log_module_gone.log)

Thanks!

**Comment by oldsoft3000** [comment]
Me too, any ideas ?

**Comment by slonopot** [comment]
I ended up upgrading Bliss to the latest version and moving to Zygisk for KernelSU, it works this way at the moment, maybe Magisk will work to. A lot of work has been done on Bliss since initially reporting this.
