### ISSUE TITLE
fix_mirror_mount.sh fails to correct mirror data mount if SRC doesn't exist

### ISSUE THREAD

**Issue by xAffan** [HuskyDG/initrd-magisk#4]
I install it using method 2 it works fine magisk app good and all I used unsu to remove su binary of rom then I enable zygisk it work good then install a module lsposed but it got installed and work fine but installed module lists not show in magisk app it empty but module work fine

TLDR
Magisk app isn't showing installed modules list but the modules work fine.

**Comment by HuskyDG** [comment]
Is your Android-x86 installed in `ext4` or `ntfs` partition?
If it is installed in `ext4` partition, `/data` is not seperated and we have to use some workaround because magisk will mount entire disk into data mirror.
Can you send `record_logs.txt` after this?
```
cat $(magisk --path)/emu/record_logs.txt >/sdcard/record_logs.txt
```
What is output of these command:
```
ls -i /data
ls -i $(magisk --path)/.magisk/mirror/data
ls -id /data/adb/modules
ls -id $(magisk --path)/.magisk/mirror/data/adb/modules
ls -id $(magisk --path)/.magisk/modules
```

**Comment by xAffan** [comment]
I use ext3 partition and it contains data folder not data.img
[record_logs.txt](https://github.com/HuskyDG/initrd-magisk/files/8505032/record_logs.txt)
Record logs are attached above.
the output of commands is in screenshot.
![Screenshot_20220418-151844_Termux](https://user-images.githubusercontent.com/59138135/163794737-19af0ae7-b2c3-4302-9112-b9e2a3bba4c9.png)

**Comment by HuskyDG** [comment]
@xAffan what is output of `cat /proc/cmdline`

**Comment by xAffan** [comment]
the output is `BOOT_IMAGE=/android-2.1.0/kernel root=/dev/ram0 quiet VULKAN=1`
(vulkan is unrelated to this issue)

**Comment by HuskyDG** [comment]
> the output is `BOOT_IMAGE=/android-2.1.0/kernel root=/dev/ram0 quiet VULKAN=1` (vulkan is unrelated to this issue)

Okey, please wait for v1.4

**Comment by xAffan** [comment]
Alright thanks 👍

**Comment by HuskyDG** [comment]
> Alright thanks 👍

@xAffan try this:

https://drive.google.com/file/d/14bzGo0O47exDvszxrokGPsseGvuMXMGV/view?usp=drivesdk

**Comment by HuskyDG** [comment]
> Alright thanks 👍

@xAffan try this:

https://drive.google.com/file/d/14bzGo0O47exDvszxrokGPsseGvuMXMGV/view?usp=drivesdk

**Comment by HuskyDG** [comment]
> Alright thanks 👍

@xAffan try this:

https://drive.google.com/file/d/14bzGo0O47exDvszxrokGPsseGvuMXMGV/view?usp=drivesdk

**Comment by xAffan** [comment]
![IMG_20220418_193642](https://user-images.githubusercontent.com/59138135/163824397-8e91fd5f-746c-4b80-8d28-3edd0b9318bd.jpg)
I faced this issue!?!?! Idk how it just panics

**Comment by xAffan** [comment]
(I used the link you sent)

**Comment by xAffan** [comment]
Can confirm the same issue - I built the image myself.

**Comment by xAffan** [comment]
It's fixed! thanks.
![Screenshot_20220419-143727_Magisk](https://user-images.githubusercontent.com/59138135/163976719-d513a7ec-289a-4d2c-a028-263562c32f2c.png)
